// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn47NDPoiBHtdrhEtrR0SWSLBf-aFv8SQ',
    appId: '1:397000885213:web:0a84ef9e8a9c5f7f712c34',
    messagingSenderId: '397000885213',
    projectId: 'whycarno-firebase',
    authDomain: 'whycarno-firebase.firebaseapp.com',
    databaseURL: 'https://whycarno-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'whycarno-firebase.appspot.com',
    measurementId: 'G-SRSPM7Q4MR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLqXTyJrX-lGYQEEGwFTr8_kT7Xm9ft1I',
    appId: '1:397000885213:android:e9df61bb678e30b7712c34',
    messagingSenderId: '397000885213',
    projectId: 'whycarno-firebase',
    databaseURL: 'https://whycarno-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'whycarno-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA0RxXyBqE6Iyfxt8q_8HUhler9qidUic',
    appId: '1:397000885213:ios:63a24ea923714fbf712c34',
    messagingSenderId: '397000885213',
    projectId: 'whycarno-firebase',
    databaseURL: 'https://whycarno-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'whycarno-firebase.appspot.com',
    iosBundleId: 'com.example.whycarno',
  );
}
